version: '2.1'

services:
  #core services
  consul:
    networks:
    - secondpage_default
    image: consul
    ports:
      - "8500:8500"
    entrypoint:
    - sh
    - -c
    - 'CONSUL_UI_BETA=true consul agent -client=0.0.0.0 -dev -ui'
  rabbit:
    networks:
    - secondpage_default
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
  cassandra:
    networks:
    - secondpage_default
    image: cassandra
    ports:
      - "7000:7000"
      - "9042:9042"
      - "9160:9160"
      - "9142:9142"
    #spark
  spark:
    networks:
    - secondpage_default
    image: spark
    ports:
      - "10000:10000"
    depends_on:
      - cassandra
    entrypoint:
    - sh
    - -c
    - './sbin/start-thriftserver.sh --hiveconf hive.server2.thrift.bind.host 0.0.0.0 --jars /usr/spark-cassandra-connector/spark-cassandra-connector/target/full/scala-2.11/spark-cassandra-connector-assembly-2.0.8-89-gd8a3eb4.jar --driver-class-path /usr/spark-cassandra-connector/spark-cassandra-connector/target/full/scala-2.11/spark-cassandra-connector-assembly-2.0.8-89-gd8a3eb4.jar --packages datastax:spark-cassandra-connector:2.3.0-s_2.11 --conf spark.cassandra.connection.host=cassandra && ./sbin/start-all.sh --hiveconf hive.server2.thrift.bind.host 0.0.0.0 --jars /usr/spark-cassandra-connector/spark-cassandra-connector/target/full/scala-2.11/spark-cassandra-connector-assembly-2.0.8-89-gd8a3eb4.jar --driver-class-path /usr/spark-cassandra-connector/spark-cassandra-connector/target/full/scala-2.11/spark-cassandra-connector-assembly-2.0.8-89-gd8a3eb4.jar --packages datastax:spark-cassandra-connector:2.3.0-s_2.11 --conf spark.cassandra.connection.host=cassandra && tail -f /etc/hosts'

  #rssparse
  rssparse-nginx:
    networks:
    - secondpage_default
    image: rlewkowicz/rssparse:nginx-1.0.0
    ports:
    #   - "443:443"
    - "8080:80"
    depends_on:
      - rssparse-php-fpm
    volumes:
    - ./secondpage-rssparse:/var/www
  rssparse-php-fpm:
    networks:
    - secondpage_default
    image: rlewkowicz/rssparse:php-fpm-1.0.0
    volumes:
    - ./secondpage-rssparse:/var/www

  #api
  api-nginx:
    networks:
    - secondpage_default
    image: rlewkowicz/api:pagespeed-1.0.0
    ports:
      - "80:80"
    # volumes:
    # - ./secondpage-api:/var/www
    depends_on:
      - api-php-fpm
    # entrypoint:
    # - sh
    # - -c
    # - 'tail -f /etc/hosts'
  # api-varnish:
  #   networks:
  #   - secondpage_default
  #   image: rlewkowicz/api:varnish-1.0.0
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #   depends_on:
  #     - api-nginx
  #   entrypoint:
  #   - sh
  #   - -c
  #   - 'tail -f /etc/hosts'
  api-php-fpm:
    # volumes:
    # - ./secondpage-api:/var/www
    networks:
    - secondpage_default
    image: rlewkowicz/api:php-fpm-1.0.0
    depends_on:
      - consul

  #render
  render:
    networks:
    - secondpage_default
    image: render
    ports:
      - "3000:3000"
    entrypoint:
    - sh
    - -c
    - 'cd /secondpage-render && npm start'

  #python-utils
  python-utils:
    networks:
    - secondpage_default
    image: rlewkowicz/python-utils-1.0.0
    depends_on:
      - rssparse-nginx
      - consul
    entrypoint:
    - sh
    - -c
    - 'sleep 15 && curl rssparse-nginx/Lifestyle && python writetoqueue.py && python consumefromqueue.py'
    # - 'sleep 75 &&  tail -f /etc/hosts'
    # volumes:
    # - ./secondpage-pythonutils/:/secondpage-pythonutils/
  #python-utils
  python-utils1:
    networks:
    - secondpage_default
    image: rlewkowicz/python-utils-1.0.0-sb
    depends_on:
      - rssparse-nginx
      - consul
    entrypoint:
    - sh
    - -c
    - 'sleep 75 && python consumefromqueue.py'
    # - 'sleep 75 &&  tail -f /etc/hosts'
    # volumes:
    # - ./secondpage-pythonutils/:/secondpage-pythonutils/
  #python-utils
  python-utils2:
    networks:
    - secondpage_default
    image: rlewkowicz/python-utils-1.0.0-sb
    depends_on:
      - rssparse-nginx
      - consul
    entrypoint:
    - sh
    - -c
    - 'sleep 75 && python consumefromqueue.py'
    # - 'sleep 75 &&  tail -f /etc/hosts'
    # volumes:
    # - ./secondpage-pythonutils/:/secondpage-pythonutils/
  #python-utils
  python-utils3:
    networks:
    - secondpage_default
    image: rlewkowicz/python-utils-1.0.0-sb
    depends_on:
      - rssparse-nginx
      - consul
    entrypoint:
    - sh
    - -c
    - 'sleep 75 && python consumefromqueue.py'
    # - 'sleep 75 &&  tail -f /etc/hosts'
    # volumes:
    # - ./secondpage-pythonutils/:/secondpage-pythonutils/
  #python-utils
  python-utils4:
    networks:
    - secondpage_default
    image: rlewkowicz/python-utils-1.0.0-sb
    depends_on:
      - rssparse-nginx
      - consul
    entrypoint:
    - sh
    - -c
    - 'sleep 75 && python consumefromqueue.py'
    # - 'sleep 75 &&  tail -f /etc/hosts'
    # volumes:
    # - ./secondpage-pythonutils/:/secondpage-pythonutils/
  python-utils5:
    networks:
    - secondpage_default
    image: rlewkowicz/python-utils-1.0.0-sb
    depends_on:
      - rssparse-nginx
      - consul
    entrypoint:
    - sh
    - -c
    - 'sleep 75 && python consumefromqueue.py'
    # - 'sleep 75 &&  tail -f /etc/hosts'
    # volumes:
    # - ./secondpage-pythonutils/:/secondpage-pythonutils/
  python-utils6:
    networks:
    - secondpage_default
    image: rlewkowicz/python-utils-1.0.0-sb
    depends_on:
      - rssparse-nginx
      - consul
    entrypoint:
    - sh
    - -c
    - 'sleep 75 && python consumefromqueue.py'
    # - 'sleep 75 &&  tail -f /etc/hosts'
    # volumes:
    # - ./secondpage-pythonutils/:/secondpage-pythonutils/
  python-utils7:
    networks:
    - secondpage_default
    image: rlewkowicz/python-utils-1.0.0-sb
    depends_on:
      - rssparse-nginx
      - consul
    entrypoint:
    - sh
    - -c
    - 'sleep 75 && python consumefromqueue.py'
    # - 'sleep 75 &&  tail -f /etc/hosts'
    # volumes:
    # - ./secondpage-pythonutils/:/secondpage-pythonutils/
  python-utils8:
    networks:
    - secondpage_default
    image: rlewkowicz/python-utils-1.0.0-sb
    depends_on:
      - rssparse-nginx
      - consul
    entrypoint:
    - sh
    - -c
    - 'sleep 75 && python consumefromqueue.py'
    # - 'sleep 75 &&  tail -f /etc/hosts'
    # volumes:
    # - ./secondpage-pythonutils/:/secondpage-pythonutils/
  python-utils9:
    networks:
    - secondpage_default
    image: rlewkowicz/python-utils-1.0.0-sb
    depends_on:
      - rssparse-nginx
      - consul
    entrypoint:
    - sh
    - -c
    - 'sleep 75 && python consumefromqueue.py'
    # - 'sleep 75 &&  tail -f /etc/hosts'
    # volumes:
    # - ./secondpage-pythonutils/:/secondpage-pythonutils/
  python-utils10:
    networks:
    - secondpage_default
    image: rlewkowicz/python-utils-1.0.0-sb
    depends_on:
      - rssparse-nginx
      - consul
    entrypoint:
    - sh
    - -c
    - 'sleep 75 && python consumefromqueue.py'
    # - 'sleep 75 &&  tail -f /etc/hosts'
    # volumes:
    # - ./secondpage-pythonutils/:/secondpage-pythonutils/
  python-utils11:
    networks:
    - secondpage_default
    image: rlewkowicz/python-utils-1.0.0-sb
    depends_on:
      - rssparse-nginx
      - consul
    entrypoint:
    - sh
    - -c
    - 'sleep 75 && python consumefromqueue.py'
    # - 'sleep 75 &&  tail -f /etc/hosts'
    # volumes:
    # - ./secondpage-pythonutils/:/secondpage-pythonutils/
  python-utils12:
    networks:
    - secondpage_default
    image: rlewkowicz/python-utils-1.0.0-sb
    depends_on:
      - rssparse-nginx
      - consul
    entrypoint:
    - sh
    - -c
    - 'sleep 75 && python consumefromqueue.py'
    # - 'sleep 75 &&  tail -f /etc/hosts'
    # volumes:
    # - ./secondpage-pythonutils/:/secondpage-pythonutils/
  python-utils13:
    networks:
    - secondpage_default
    image: rlewkowicz/python-utils-1.0.0-sb
    depends_on:
      - rssparse-nginx
      - consul
    entrypoint:
    - sh
    - -c
    - 'sleep 75 && python consumefromqueue.py'
    # - 'sleep 75 &&  tail -f /etc/hosts'
    # volumes:
    # - ./secondpage-pythonutils/:/secondpage-pythonutils/
  python-utils14:
    networks:
    - secondpage_default
    image: rlewkowicz/python-utils-1.0.0-sb
    depends_on:
      - rssparse-nginx
      - consul
    entrypoint:
    - sh
    - -c
    - 'sleep 75 && python consumefromqueue.py'
    # - 'sleep 75 &&  tail -f /etc/hosts'
    # volumes:
    # - ./secondpage-pythonutils/:/secondpage-pythonutils/

  python-utils-watcher:
    networks:
    - secondpage_default
    image: rlewkowicz/python-utils-1.0.0-sb
    depends_on:
      - rssparse-nginx
      - consul
    restart: always
    entrypoint:
    - sh
    - -c
    - 'sleep 100 && python writetoqueue.py'
    # - 'sleep 75 &&  tail -f /etc/hosts'
    # volumes:
    # - ./secondpage-pythonutils/:/secondpage-pythonutils/

networks:
  secondpage_default:
    ipam:
      config:
        - subnet: 192.168.5.0/24
