version: '2.1'

services:
  #core services
  consul:
    dns: ${DNS:-8.8.8.8}
    image: consul
    ports:
      - "8500:8500"
    entrypoint:
    - sh
    - -c
    - 'CONSUL_UI_BETA=true consul agent -client=0.0.0.0 -dev -ui'
  rabbit:
    dns: ${DNS:-8.8.8.8}
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
  cassandra:
    dns: ${DNS:-8.8.8.8}
    image: cassandra
    ports:
      - "7000:7000"
      - "9042:9042"
      - "9160:9160"
      - "9142:9142"

  #rssparse
  rssparse-nginx:
    dns: ${DNS:-8.8.8.8}
    image: rlewkowicz/rssparse:nginx-1.0.0
    # ports:
    #   - "443:443"
    #   - "80:80"
    depends_on:
      - rssparse-php-fpm
  rssparse-php-fpm:
    image: rlewkowicz/rssparse:php-fpm-1.0.0


#api
  api-nginx:
    dns: ${DNS:-8.8.8.8}
    image: rlewkowicz/api:nginx-1.0.0
    volumes:
    - ./secondpage-api:/var/www
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - api-php-fpm
  api-php-fpm:
    volumes:
    - ./secondpage-api:/var/www
    image: rlewkowicz/api:php-fpm-1.0.0

  #render
  render:
    dns: ${DNS:-8.8.8.8}
    image: render
    entrypoint:
    - sh
    - -c
    - 'cd /secondpage-render && npm start'

  #python-utils
  python-utils:
    dns: ${DNS:-8.8.8.8}
    image: python-utils
    entrypoint:
    - sh
    - -c
    - 'tail -f /etc/hosts'
    volumes:
    - ./secondpage-pythonutils/:/secondpage-pythonutils/
